### ISSUE TITLE
Add Typescript evaluation support

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#13]
Let's add another language to the project! 

So far, we have Python via pyodide. 

Need to start thinking about the API for how we'll load and run code from various different languages. 

Happy to have someone add typescript evaluation support. 

Seems like AssemblyScript is the go to for this. https://www.assemblyscript.org/examples/mandelbrot.html#example

**Comment by S-codes14** [comment]
you can also add react via [react-live](https://github.com/FormidableLabs/react-live)

**Comment by hatemhosny** [comment]
may be this can guide in adding AssemblyScript

https://github.com/live-codes/livecodes/blob/49ec7656ef45f59945712763ef539ed2601277e7/src/livecodes/languages/lang-assemblyscript.ts

You can see it working here
https://dev.livecodes.io/?template=assemblyscript

**Comment by hatemhosny** [comment]
In fact you can run the typescript compiler itself in the browser. But this compiles typescript to javascript not wasm.

Let me know if you want me to elaborate along that route.

**Comment by jsjoeio** [comment]
How difficult would this be to implement?

**Comment by nikolaystrikhar** [comment]
@hatemhosny I'm trying to play with it, but the problem is that with Python we just run the code and get it's output. And with AssemblyScript we can compile TS, use exported functions in js (like in example), but I'm stuck on the next step.

How can I run the TS code instead of compiling it? I spend a few hours on it, but can't find any info. Maybe I'm too tired already.

Let me know if you find something about it.

**Comment by jsjoeio** [comment]
I wonder if we can draw from the TypeScript Playground like [this one](https://github.com/fabiandev/typescript-playground) for example?

**Comment by jsjoeio** [comment]
Argh, I wish I knew where to start to be able to contribute more. Basically, we need way to evaluate TypeScript code in the browser right?

Any tips for where to start?

**Comment by nikolaystrikhar** [comment]
@jsjoeio I spent several hours playing with assemblyscript, but have not found the way to do it with. Maybe I'm not smart enough, it's not my current stack, but even their example on the home page shows that you can export, but not transpile. Or at least I have not found the way.

So maybe it was not the right way from the beginning. But I think someone must check it as well as I'm not confident about it. So then we could know for sure it's not an option and fine an alternative.

**Comment by jsjoeio** [comment]
I don't know if I'm smart enough to figure it out either but at least you tried 😂

Yeah, sounds good. Would LOVE to see this implemented so hopefully someone smarter can give us pointers.

**Comment by kennethcassel** [comment]
@nikolaystrikhar how about instead of wondering if you're not smart enough, we all assume we all have the capability of implementing this feature! 

It might take more digging, experimenting, debugging, than a few hours. 

Maybe it takes understanding the difference between JS, TS, AssemblyScript, WASM and/or the related tooling. 

Point being is there is always some way to approach and find a solution. 

It might not be as intuitive or as straight forward as you'd hope. 

Best of luck figuring it out! 

I'll try to find some resources that I can put together so folks can understand the landscape easier!

**Comment by kennethcassel** [comment]
Zack mentioned possibly being able to use the swc.rs wasm build target to do TS evaluation. 

Essentially you'd use the wasm based swc.rs to transpile TypeScript into Javascript in the browser and then run the JS through `eval()`

**Comment by hatemhosny** [comment]
I am by no means a WebAssembly or AssemblyScript expert, but these are what I have learnt in the past few months:

- [WebAssembly must currently be loaded and compiled by JavaScript](https://webassembly.org/getting-started/js-api/). WebAssembly also does not have access to the DOM and the rest of web APIs, so JavaScript code has to provide that.
- Pyodide is already doing that for us, through its API [`pyodide.runPython`](https://pyodide.org/en/stable/usage/quickstart.html#running-python-code). This is also the case in most other platforms compiling to wasm, they provide a JavaScript loader/wrapper e.g. Go, blazor, etc.
- In AssemblyScript, you have to do that yourself, or use its loader. This is how you load the AssemblyScript module in html page ([from AssemblyScript official demo](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIHZhciBhID0gMCwgYiA9IDEKICBpZiAobiA+IDApIHsKICAgIHdoaWxlICgtLW4pIHsKICAgICAgbGV0IHQgPSBhICsgYgogICAgICBhID0gYgogICAgICBiID0gdAogICAgfQogICAgcmV0dXJuIGIKICB9CiAgcmV0dXJuIGEKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=)):
``` html
<textarea id="output" style="height: 100%; width: 100%" readonly></textarea>
<script>
loader.instantiate(module_wasm, { /* imports */ })
  .then(({ exports }) => {
    const output = document.getElementById('output')
    for (let i = 0; i <= 10; ++i) {
      output.value += `fib(${i}) = ${exports.fib(i)}\n`
    }
  })
</script>
```
- So you may either allow the user to write JavaScript code that consumes the exported wasm modules, or provide a wrapper for it as API for the library.
- AssemblyScript is NOT TypeScript running in wasm. There are [significant differences](https://www.assemblyscript.org/basics.html#strictness). It is nice to provide AssemblyScript support, though. But I would not consider that providing support for TypeScript.
- as @kennethcassel mentioned, you may use [swc compiled to wasm](https://swc.rs/repl#%7B%22rawCode%22%3A%22%5Cn%20%20class%20Project%20%7B%5Cn%20%20%20%20constructor(name)%20%7B%5Cn%20%20%20%20%20%20this.name%20%3D%20name%5Cn%20%20%20%20%7D%5Cn%20%20%7D%3B%5Cn%5Cn%20%20export%20class%20SwcProject%20extends%20Project%20%7B%5Cn%20%20%20%20constructor(name%2C%20version)%20%7B%5Cn%20%20%20%20%20%20super(name)%3B%5Cn%20%20%20%20%20%20this.version%20%3D%20'20210629'%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20showOff()%20%7B%5Cn%20%20%20%20%20%20console.log('swc%20is%20a%20useful%20project')%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%22%2C%22rawConfig%22%3A%22%7B%7D%22%7D) to compile TypeScript to JavaScript and then run it (not wasm, though). [Esbuild also has a wasm version](https://esbuild.github.io/getting-started/#wasm). However, if you are compiling TypeScript to JavaScript (not wasm), why don't you just use the official TypeScript compiler! We need to differentiate here between using a compiler running in wasm or running the code itself is wasm.
- I would be cautious running JavaScript code using `eval` in [non-sandboxed iframe](https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/) for security reasons.

**Comment by kennethcassel** [comment]
My preference would be for allowing users to have as close to a "real" typescript experience as possible. I think allow users to write TypeScript, then compile and evaluate would be the move I'd most prefer. 

This is different than pyodide, but JS is a special case. 

Also, preference for swc vs TypeScript compiler is around speed.

**Comment by Dhaiwat10** [comment]
I've hacked a prototype-ish for this. This does not support type-checking etc but it does **transpile** the TS code into JS, runs it & spits out the result. 

```html
<script src="https://unpkg.com/typescript@latest/lib/typescriptServices.js"></script>
<script>
  // To 'store' console.logs so that we can read them later for output
  console.stdlog = console.log.bind(console);
  console.logs = [];
  console.log = function () {
    console.logs.push(Array.from(arguments));
    console.stdlog.apply(console, arguments);
  }

  // Typescript code to be transpiled
  const tsCode = `
  function add(a: number, b: number): number {
    return a + b;
  }

  console.log(add(1, 2));
`;

  // Transpiling from TS to JS
  const jsCode = window.ts.transpile(tsCode);
  // Displaying the transpiled code
  document.write(jsCode + '<br /><hr />');
  
  // Running the transpiled code
  const result = eval(jsCode);
  // Displaying the result
  document.write(console.logs);
</script>
```

**Comment by Dhaiwat10** [comment]
This is not _really_ compilation tho. And it's probably slow if put under stress. But I think it's something to start from.

**Comment by Dhaiwat10** [comment]
I just saw that you prefer swc. That's probably a good call. I think I'm gonna see if we can run that in the browser & get back to you folks here. :)

**Comment by Dhaiwat10** [comment]
^^^ I built a basic UI around this, if anyone's interested in trying this out. 

https://ts-sandbox.vercel.app

https://github.com/dhaiwat10/ts-sandbox

**Comment by kennethcassel** [comment]
This is really cool @Dhaiwat10! getting close 🔥

A comparison between this and using swc and any downsides/trade offs between the two would be great for deciding ultimately which approach to use.


Thanks a lot for working on it

**Comment by zackradisic** [comment]
Main benefit for swc should be speed, but now that I think about it the difference in speed will probably negligible for small code snippets targeting es6 syntax with no optimizations, you can see in @Dhaiwat10's example very fast. Also swc doesn't type check, which could be a deal breaker.

Would still like to try out and benchmark swc against tsc just for fun,  will play around with that tomorrow!

**Comment by Dhaiwat10** [comment]
@zackradisic I'm not really sure how to stress-test this. Looking forward to hearing from you about swc. Let me know if you find a way to run it in the browser!

**Comment by kennethcassel** [comment]
> Main benefit for swc should be speed, but now that I think about it the difference in speed will probably negligible for small code snippets targeting es6 syntax with no optimizations, you can see in @Dhaiwat10's example very fast. Also swc doesn't type check, which could be a deal breaker.
> 
> 
> 
> Would still like to try out and benchmark swc against tsc just for fun,  will play around with that tomorrow!

Ah didn't realize swc didn't type check. This makes me want to go with the regular TS compiler instead

**Comment by kennethcassel** [comment]
@Dhaiwat10 if you wanted to make a PR with your current approach, we'd merge it in :) 

The trade offs would be cool to know but now knowing swc doesn't do type checking, it makes sense to use your approach instead!

**Comment by zackradisic** [comment]
Yeah, I second the choice on tsc. For those still interested in seeing swc in action I forked @Dhaiwat10's playground and added swc transpilation support. Check it out [here](https://ts-sandbox-swc.vercel.app/). swc is on the order of 8-10x faster than tsc, but for small files that means something like 4ms vs 32ms which is hardly perceivable.

**Comment by Dhaiwat10** [comment]
> @Dhaiwat10 if you wanted to make a PR with your current approach, we'd merge it in :) 
> 
> The trade offs would be cool to know but now knowing swc doesn't do type checking, it makes sense to use your approach instead! 

Sounds good. I'll make a PR soon 👍

**Comment by Dhaiwat10** [comment]
Hey, @kennethcassel there's still one issue that we need to look at. Atm, even if the code has invalid types, the editor will show the errors but the code will still execute. We need to address that! I was planning on fixing this tomorrow but I saw you merged the PR, no worries! But we def need to address this. (or do we? Your call, haha!)

**Comment by kennethcassel** [comment]
Haha yeah you can fix it! I like to ship and iterate. What you have works but like you said is missing a big piece of the puzzle. 

I'll open a separate issue for that!
