### ISSUE TITLE
Remove video from README and replace with a short GIF of the project

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#25]
The video already is pretty outdated, a short gif showing the code execution would be cool in the readme

**Comment by nikolaystrikhar** [comment]
I agree, but maybe it should be done a bit later after we have #26 sorted out.

**Comment by S-codes14** [comment]
done https://github.com/slipHQ/run-wasm/pull/27

**Comment by kennethcassel** [comment]
Keeping this open since we still want a gif of the updates code editor

**Comment by jsjoeio** [comment]
Can I work on this one?

**Comment by kennethcassel** [comment]
Would love that @jsjoeio!
