### ISSUE TITLE
Change copy above the code editor in example-nextjs

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#26]
We should have a short description of the project above the code editor.

Kind of a weird experience to have it print out the code and language it's executing above the code editor. 

Change the copy to better explain what a user can do with the project

**Comment by mcintyre94** [comment]
I was looking at this earlier too, do you think it'd be worth dropping the `RunWasm` function in src/index.tsx? There's probably no UI beyond the code editor that's going to be relevant to every consumer of run-wasm so IMO this belongs in `example-nextjs` instead.

**Comment by kennethcassel** [comment]
I imagine RunWasm inside of src/index.tsx being a very basic code editor + output element that people can just drop into their website. 

Folks who don't want to mess with the api but just want a place to embed a code snippet and have it be executable
