### ISSUE TITLE
Add Jest for unit testing 

### ISSUE THREAD

**Issue by jsjoeio** [slipHQ/run-wasm#42]
What are everyone's thoughts around adding Jest for unit test `src`? (Not the Next.js site, but that could come later)

Would you accept a PR if I added this?

**Comment by kennethcassel** [comment]
Yup this is cool :) def would accept a pr adding tests to the library!

**Comment by kennethcassel** [comment]
btw thanks for streaming the process! @all-contributors add @jsjoeio for his awesome twitch content :)
