### ISSUE TITLE
Typescript will execute code even if there are type errors

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#52]
Hey, @kennethcassel there's still one issue that we need to look at. Atm, even if the code has invalid types, the editor will show the errors but the code will still execute. We need to address that! I was planning on fixing this tomorrow but I saw you merged the PR, no worries! But we def need to address this. (or do we? Your call, haha!)

_Originally posted by @Dhaiwat10 in https://github.com/slipHQ/run-wasm/issues/13#issuecomment-928013431_

**Comment by Dhaiwat10** [comment]
Adding a bit of context. We're currently _transpiling_ the TS code into JS & then eval'ing it. Not _compiling_ it. This is why in case of type errors, the editor will correctly signal that there's an error but the code will regardless be executed.

**Comment by mcintyre94** [comment]
Not sure if changing to compiling is easy, ignore me if it is! But if it's tricky then it looks like there's an API to get the errors from the editor `getModelMarkers()`: https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#getmodelmarkers 

So we could use that to disable the run button in the example if there are errors as a short term fix.

**Comment by zackradisic** [comment]
I noticed the other day that swc and `ts.transpile()` both didn't typecheck and found [this](https://github.com/Microsoft/TypeScript/issues/7402), says we need to use `ts.createProgram()`. Haven't tried it but there's an example [here](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/typescript-vfs#a-full-example) that looks simple enough to implement

**Comment by hatemhosny** [comment]
@zackradisic that's true.
based on [this](https://stackoverflow.com/a/53764522): [here is a basic demo](https://dev.livecodes.io/#code/N4IgLglmA2CmIC4QBUCeAHWBnAxgJwnTAAIATCAQwHMA7Aey0hyxABoRTt9DI6bEQbcNRYIA2oIC67CjkgA3WAFFyYOngG4CRIQFsKeANYBXdIlDQKNKserwkACzC7oQnHzCwaYAQB4tPMRYeDgAvAA6IE5g6FgIAPTxxjTohlQAdO668WAYXNpgAAIALOkAzOXx0BAARjl5AUQAyrB48hA42OkAVliRAHy+8Y1g/eE0vuh4sMQQpBEgdMYxywNDU7Bj/Ozu3l5gAKp4rkhCWLBwcuoCIAC+7IyocOYglta2VPYgzCw7HvsCdycYjAcJ4cbEYg1WRpPBLGikAC07mg6gQxDwVBqAAoAExlABsrGI+IArMSyQBKADcYIhZAgWHQllQ6IgNGqNFgiJqqJwhlp4JokPQFFI5Gs6IAjLBdIL6TV1Jw8NL0AAPIJ0aqkMgGWGwVDy4VQpWtRF4MUQYxxYik9VGyH6THs6Wyo23Nz/bxHE6CB4XWBXDSne4gEYvN42OwCboUeQUcN/PbeASJKEJ2A6vjEaKxBLDMAwuiKPAAM1RAHdMnRshR4qSygB2AnFUm43F0mid0vJOQQbOfMAAEUotAYTCwADF1MhYGqwNjPPPKSDO5DIbtGGRjLpdKhJxA4AAFChgBzEULESLxUuH2DpMB9EAO9ebkhLsAAQS3l8fmWmp6wE0SwhLAB5wNipA7nu4GwCeZ7Eh+iFYOkTTcEQyAGIO6QADKAYwNJrq+fBbnQRD9jQWAXiCtwvhuJEkA447UaCQrruxxC3nAShqoyj7olxcGnueoT9Jxd7wSJoSXlBu77hJwmsERHEMtMQaoDxfE2uQeCSReYk6Xp0mXtekRKWxKnEIOADCxh4NM3gjmpah4KyxDYiuolXiA8RmcpHGDk5gYuRA2Doh5+nEGI0j+exNlWHwHQUNAsEAHIULosACXe6WZZFgm5bA5n0ipg6pbAFY4eyWXuZ5YmROE4x+RZpWwMOsClhQxjQGAVU1GlGU1RFXkNWwsXroOwF2Z0sHZcewn5QpZ4XtJ25ybBekAPzEB+34kOiyScLeXKkMVxoqQBpCzeJ83LV5glGatskwUt57bR+xAHQiHXVad42QtasDWRmLSUVAECKANmU2sNYlgHgxhFf9xAVgQnjXbDNH+bR/lvsQUx0FQFq6NRf74LAgFHnCRMZdirElRxZG8JRZ2WRidB0GAhU2mIz3ybdDgxS1HFMYw2OEUK/nTGAdnCn+g5U8ouhQCO1D0IwHRYNiBM07oEvjLcnadnjQIzJeAAGxsMcQaroowBDWNRpLUleQp46g1Fquk8bQIjRp4wAXtRWA1rAABqyV+525sPgQuhNIWeALvrXZu9b0NYHYVGXoFo7qxO054LO87YqblL+ekXGeHgkGRaQld3uXwvpPo6C1159cZ3YxdgCnnakHQOA7vs6QAI6I65LSXC52IAOQAMRLCsYCz5S6TslyeAABLIAAsjh1H+bPpvoo1NCz8QADUR++Kb/QX5fxCm1fxCz0Md9nw/R9d58Npn5/V9/IACkmgAHlUrpHtuyKgEBSyoGxD/bAxIaDdWgBSFOnpkyHGODcf009rghgeLkOAWAHCwDaqIaKDx0KPkQFQ74WAsCK3OD4U47ACadEYeoUQoB0Djh+C8LqagNi3jVK0RAnVoDnHYfwxhzC2pKBoPICRyVpHCEPBWdkpABEIEkecW4oYh6MBrC0MAkBrA8PALKZkgEXikFPBQcwoYNgOWVIgeGiMDHsAgLoPhSceGhlyJgAJ7ASxYAogIAADOkUokS7hAA)

**Comment by Dhaiwat10** [comment]
> @zackradisic that's true.
> based on [this](https://stackoverflow.com/a/53764522): [here is a basic demo](https://dev.livecodes.io/#code/N4IgLglmA2CmIC4QBUCeAHWBnAxgJwnTAAIATCAQwHMA7Aey0hyxABoRTt9DI6bEQbcNRYIA2oIC67CjkgA3WAFFyYOngG4CRIQFsKeANYBXdIlDQKNKserwkACzC7oQnHzCwaYAQB4tPMRYeDgAvAA6IE5g6FgIAPTxxjTohlQAdO668WAYXNpgAAIALOkAzOXx0BAARjl5AUQAyrB48hA42OkAVliRAHy+8Y1g/eE0vuh4sMQQpBEgdMYxywNDU7Bj/Ozu3l5gAKp4rkhCWLBwcuoCIAC+7IyocOYglta2VPYgzCw7HvsCdycYjAcJ4cbEYg1WRpPBLGikAC07mg6gQxDwVBqAAoAExlABsrGI+IArMSyQBKADcYIhZAgWHQllQ6IgNGqNFgiJqqJwhlp4JokPQFFI5Gs6IAjLBdIL6TV1Jw8NL0AAPIJ0aqkMgGWGwVDy4VQpWtRF4MUQYxxYik9VGyH6THs6Wyo23Nz/bxHE6CB4XWBXDSne4gEYvN42OwCboUeQUcN/PbeASJKEJ2A6vjEaKxBLDMAwuiKPAAM1RAHdMnRshR4qSygB2AnFUm43F0mid0vJOQQbOfMAAEUotAYTCwADF1MhYGqwNjPPPKSDO5DIbtGGRjLpdKhJxA4AAFChgBzEULESLxUuH2DpMB9EAO9ebkhLsAAQS3l8fmWmp6wE0SwhLAB5wNipA7nu4GwCeZ7Eh+iFYOkTTcEQyAGIO6QADKAYwNJrq+fBbnQRD9jQWAXiCtwvhuJEkA447UaCQrruxxC3nAShqoyj7olxcGnueoT9Jxd7wSJoSXlBu77hJwmsERHEMtMQaoDxfE2uQeCSReYk6Xp0mXtekRKWxKnEIOADCxh4NM3gjmpah4KyxDYiuolXiA8RmcpHGDk5gYuRA2Doh5+nEGI0j+exNlWHwHQUNAsEAHIULosACXe6WZZFgm5bA5n0ipg6pbAFY4eyWXuZ5YmROE4x+RZpWwMOsClhQxjQGAVU1GlGU1RFXkNWwsXroOwF2Z0sHZcewn5QpZ4XtJ25ybBekAPzEB+34kOiyScLeXKkMVxoqQBpCzeJ83LV5glGatskwUt57bR+xAHQiHXVad42QtasDWRmLSUVAECKANmU2sNYlgHgxhFf9xAVgQnjXbDNH+bR/lvsQUx0FQFq6NRf74LAgFHnCRMZdirElRxZG8JRZ2WRidB0GAhU2mIz3ybdDgxS1HFMYw2OEUK/nTGAdnCn+g5U8ouhQCO1D0IwHRYNiBM07oEvjLcnadnjQIzJeAAGxsMcQaroowBDWNRpLUleQp46g1Fquk8bQIjRp4wAXtRWA1rAABqyV+525sPgQuhNIWeALvrXZu9b0NYHYVGXoFo7qxO054LO87YqblL+ekXGeHgkGRaQld3uXwvpPo6C1159cZ3YxdgCnnakHQOA7vs6QAI6I65LSXC52IAOQAMRLCsYCz5S6TslyeAABLIAAsjh1H+bPpvoo1NCz8QADUR++Kb/QX5fxCm1fxCz0Md9nw/R9d58Npn5/V9/IACkmgAHlUrpHtuyKgEBSyoGxD/bAxIaDdWgBSFOnpkyHGODcf009rghgeLkOAWAHCwDaqIaKDx0KPkQFQ74WAsCK3OD4U47ACadEYeoUQoB0Djh+C8LqagNi3jVK0RAnVoDnHYfwxhzC2pKBoPICRyVpHCEPBWdkpABEIEkecW4oYh6MBrC0MAkBrA8PALKZkgEXikFPBQcwoYNgOWVIgeGiMDHsAgLoPhSceGhlyJgAJ7ASxYAogIAADOkUokS7hAA)

Correct me if I'm wrong — the `ts.getPreEmitDiagnostics(program)` method only does type-checking & doesn't actually compile/transpile the code, right? If yes, we have two options:

1) Compile the code using the approach @zackradisic shared. (I'm assuming that would include type-checking)
2) Do type-checking using your code & only _then_ transpile the code. 

Which option looks better? Open to hearing everyone's thoughts.

**Comment by Dhaiwat10** [comment]
I'm caught up in two minds because I'm not sure if compiling is significantly slower than transpiling. I have no knowledge/experience about this. 😅

**Comment by hatemhosny** [comment]
> Correct me if I'm wrong — the `ts.getPreEmitDiagnostics(program)` method only does type-checking & doesn't actually compile/transpile the code, right? 

Yes, that's right. 

> Which option looks better? Open to hearing everyone's thoughts.

It depends what behavior we want. I think type-checking followed by transpile if it succeeds is a reasonable approach so long as we show the user clear messages for what went wrong. 

Another approach would be allowing the library user to choose by setting an API option. 

> I'm caught up in two minds because I'm not sure if compiling is significantly slower than transpiling. I have no knowledge/experience about this.

https://stackoverflow.com/questions/44931479/compiling-vs-transpiling
Technically typescript is a transpiler to javascript.

**Comment by kennethcassel** [comment]
>  It depends what behavior we want. I think type-checking followed by transpile if it succeeds is a reasonable approach so long as we show the user clear messages for what went wrong.

I agree here! This seems like a good approach.

**Comment by kennethcassel** [comment]
Awesome, go for it @Dhaiwat10 :)
