### ISSUE TITLE
Fix fathom analytics

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#53]
Need to complete Fathom Analytics setup so we can measure traffic on the runwasm.com site 

The fathom analytics dashboard for runwasm.com is here: https://app.usefathom.com/share/pecjvoqv/runwasm.com

Documentation for adding it to a next.js project is here: https://usefathom.com/docs/integrations/next

**Comment by kennethcassel** [comment]
Fixed with #55 :)

**Comment by nikolaystrikhar** [comment]
<img width="1312" alt="Screenshot 2021-09-27 at 19 55 24" src="https://user-images.githubusercontent.com/4025589/134960221-a348190f-ecc0-4751-9c80-237b896087e8.png">

Woohoo :-)
