### ISSUE TITLE
Add OG Image to next.js project

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#59]
Big believer that design and good style can help elevate an OSS project. 

It'd be great to have this image added as an Open-Graph image so folks will see the logo when the link is shared in various places. 

![run-wasm-logo](https://user-images.githubusercontent.com/22961671/135013980-1819abf7-2d05-4b18-b14f-faa83a4c9e62.png)

**Comment by pouannes** [comment]
Hey Kenneth, can I pick up this issue?

**Comment by kennethcassel** [comment]
> Hey Kenneth, can I pick up this issue?

Go for it!
