### ISSUE TITLE
add lib support for TypeScript type checking

### ISSUE THREAD

**Issue by hatemhosny** [slipHQ/run-wasm#68]
Currently typescript type checking reports a lot of errors because it does not account for Web APIs.

This is the cause for having to [add this](https://github.com/slipHQ/run-wasm/blob/f5844edb5184eb73448de2ef17cb6cfddb04c052/src/RunWasmClient.ts#L125) to ignore reference to console. But this way we also get errors for reference to `window`, `document`, `alert`,...etc
[demo](https://dev.livecodes.io/#code/N4IgLglmA2CmIC4QBUCeAHWBnAxgJwnTAAIATCAQwHMA7Aey0hy2IAo7pSBKEAGhFLZ8hSHRqIQfcNSyIA2pIC6-CjkgA3WAFFyYOngm4CRKQFsKeANYBXdIlDQKNKterwkACzCnoUnGLBYGjAJAB4jEWIsPBwAXgAdEC8wdCwEAHp06xp0SyoAOn9TdLAMIWMwAAEAFnyAZnr06AgAIxKyiKIAZVg8dQgcbHyAKyxEgD5Q9M6wcfiaUPQ8WGIIUgSQOmsU7Ymppdg58X5-YKCwAFU8XyQpLFg4NX0JEABffkZUOHsQR2dXKjuEDMWQnALnCT+QTEYDxPDzYjEFqqPJ4LY0UgAWn80H0CGIeCoLVYACY6gA2XjEMkAViptK4AG44QiyBAsOhHKh8RAaM0aLBMS1cThLMz4TREegKKRyM58QBGWCmcWslr6QR4RXoAAeUQ4azIFlRsFQqslSI1vUxeBlEGsaWINN15sR5kJvMVyvNrz84OCVxukg+D1gTwMt3eIBmPz+LjcEmGFHUFBjYLOwQkmSRqdgpGIYmIyVSGWmYBRdE0eAAZriAO6FOjFCjpGl1ADs5OqNJJJJZNH71eyagghcBYAAIpRaAwmFgAGL6ZCwHVgViBVdcGH9xGI06MMjWUymVDziBwAAKFDAHmIsWIiXS1fPsHyYDGIFdu-3JA3YAAgge97voUyzXrAXRbDEsBnnArCkEeJ6wbAV43lSf7oVg+RdMIRDIBY475AAMuBjBMju35iAedBEKONAsPewCvF+e5USQHizne24SruvHEM+cBaDq7LvviAkodet6xOM-EvqhUmxPeCHHqecmSbwFF8WyyzhqgQkiY65B4PJd4yUZJmKfej6JBpPFacQ44AMLWHgyzBFOOl6Hg3JsFu0kPiA6Q2ZpfHjh5YZeRA2D4qwfkyXIyghbxTlOGIAwUNAyEAHIUKYsBiS+OV5aZslwEVsC2ayWnjllsB1kRvL5b5JWJPE8zBXZ1WwJOsDVhQ1jQGADUtNluVNbFLUgB1VWhd1kEuYMyEFZekkleJFmKYeKnISZAD8xB-oBJD4tkgjPgKpCVRaWlgaQS2lRJN5rWpT2WVtSEvbe+1-sQJ0Yr1jWXUlu4OrAjm5j09FQBAmijXljoTf5YB4NYFXA4idYEIE92IzJTEhcxIU-sQSx0FQtqmFxIH4LA4EXmi5O5awsKdXxNGiPRV32QSdB0GA5WOnIykfStN6JazvEcYwBPkRKIXLGALmSiB4709ophQFO1D0IwAxYKwpOM6YsvzK8-b9sTUIrPeAAGFtscQOr4owBDOFxNKMg+ErE6gXE6vkKbQKj5rEwAXlxWBNrAABqGXB-b9EcK+uJUKwADkHgQGnJsYnQOBHuc+QAI6o95PSPF56cAMRrNn5p1rypB0A2IrXnR+QeMs1bmhlvRrhnWc5zbb4EKYXTlnga45wnB7w1gbgMQ53VazOuvMIueDLqurBW1wIX5AJgR4PBJWkAfL576z+TmOgJ-+Wfc9uFvYDTxKTf53lwTF6XqDlxF+jVy2DsMA2d8i8gFHgAAEsgAAskRLiIU05W3xG1GgadiAAGpEGhCtuMdBGDiBW0wcQNOUxcGoPwYgx+gJHSoIoZgkKAApLoAB5LK+QXa8ioBAasqBWDUOwFSGgA1oD0hzn6DMlxrgvBDBXZ4kYPilDgFgDwsBuqyAQAlD4uF3zyGUMCLAWA1b3BCLcfgpNBiGP0Bo0A6BZwgh+P1PQBxnw6l6IgPq0B7jmPsYY4x3UtA0HUB4jK3jpDngbhiBxCBPH3FeFGfOjAmw9DAJAZwNjwDKk5OBH4pBrwUHsFGA4blNSIGRqjeJ-AICmDsZPGxUZSiYHqfwKsWA6ISAAAz5FqB0t4QA)
 

This can be solved by loading [lib definitions](https://www.typescriptlang.org/tsconfig#lib) for 'es5' and 'dom'.

[this is a demo](https://dev.livecodes.io/#code/N4IgLglmA2CmIC4QBUCeAHWBnAxgJwnTAAIATCAQwHMA7Aey0hyxABoRTt9DI6bEQbcNRYIA2oIC67CjkgA3WAFFyYOngG4CRIQFsKeANYBXdIlDQKNKserwkACzC7oQnHzCwaYAQB4tPMRYeDgAvAA6IE5g6FgIAPTxOKQ0AHQAVlic0BDyeKk0sGDxNOi68WAYXNpgAAIALKmNAMzxOQBGFVUBRADKsHjyEDjYGViRAHy+8T1gE+E0vuh4sMQQpBEgdMYxO5PTy7Dz-Ozu3l5gAKp4rkhCWLBwcuoCIAC+7IyocOYglta2Kj2EDMFinDwXATuTjEYDhPALYjEdqyQxUPDbGikAC07mg6gQxDwVHaAAoAEzNABsrGIlIArLSGQBKADc8MRZAgWHQllQhIgNByhWx7XxOEM7IRNCR6AopHI1kJAEZYLopZz2upOHgVegAB5BOg5UhkAxolaoDUy5HagbYvDyiDGOLEekG61I-TEwUqtXWt5uCHea63QSfR6wZ4aO4fECzX7-Gx2ATpCjyCgJ8HnbwCRLIzOwU18YjRWIJGZgVF0RR4ABm+IA7ql3OUKPF6c0AOxU+r08nkjk0IdnRjEIFgAAilFoDCYWAAYupkLB9SRQsRM6gaDhiKTPGvaXQiBA+FhmcRQhNYUOkaOSB0sJfiMfeDQsKkOsQAD7f4hiSRPWIe9xyKAAZCB2mfLcdz3DoLyvG9pSRO8zxIOUwAcZ8AANKkwWY2kgwj2lSAASYAOjeVJSFSMAsGwoDUPfEgzk8bxoMbCgoGIOsihwBxSVvFCkWwss4kSZI0kybJcnyQpilKco8OqHgGiaVJWg6YiyIoyCqJoujsKEpFmWMlDaIcLxSVJFZz0va9bNo1cwFJZlTOQ4TiBbCgwH46yEOvUdjVgT86CoQSQDrLi4FNNQeL4rCOkJSJiAAamIeC2SHMyVjAYw8BlOEPOEjCHFYMymLYsByuKlDMzAQk6JbFYfNgXpthCWAFwgOBSVK2lWIuWkmt6bgiGQAwJ1SMDWsYZkas5JE3iA5bso8kCOknHyKA4riSAABQxXRuRCihoGgUlH1SfR0FJCcIPaNzrSEkDSGMXRdFQbq4H2nysI3SJ4jrHqQroyIgJAg8wAAQTHDcmvwWBWva-KRm+2BBNqt6Pq+kHfswhabSRKHCeEkaxrACbiSKabZrAISsulF60NLOdnyKxaeJBpR9W5OjCVJYGfr+gKKq54XMMvUIN2xz70fxrDf3F2AFdSRgDDogB1KABMiZSCK0yJ5rM8gVmjVAeb511SVNhWAq5PAFalgGQHiSJSZQicAGF8pWbxpzNtQ8H5Pd7cB92zInAOoyDiBsAF+2AI9pFvasPhhjO9GADkKF0WABaF2Ac7z+3C+L2Bk9AsAs9gRsIMKBP7OISJwgWCPaqj2AouMaAwAe7Pc-z0Om5bthI6KFHOvRgu8ZF+yxcLp3pZl965dnzCxaRAB+Ygodh+nauEwlNu21Jgaxaz4KbjpUlK53lbtrfUnqyuWtIae90XuerwX9f-ulsgq9cYSwcJvYgO8oZgOPpBLaVYz6ClIJfSC9sb532Xg-EWT9BreEri6WAXtCz9HfFAXIXUQbl2tvbMAeBjAVzMo2AgngP6uSbsAD4QlVpM3WizDEdBq6DyfBuE+cCbpIMetfSCt8RbPW4cxYgywwqOl0M+BGLVPCHUUbnTGnNeH8Lzh+M4OAfKkjELLYBKs-qSGNrVV8p53yVwcHOBmMjOS5XyjKJqE5DrKGOlOGc9BGDDCwH1DE6Jc6MwWJwtu0oQLQlWBuIyMSWb6kJIwAg1hnz0lZM3JJcjUDPn1KkDM0BaHWhAgAL2fFgOgecABqZ1SkjjPMFUK4UADkDgIBtIiViOgOB3oXFSAAR1ocHfoTwg6kjaQAYnWN060jYEF0GbOKHydjUgOBWHWa0Z0BguQ6V0np2FaIEF0L0KseAXI9KaXI2xZ52ZCSSv+SI2B6Tu2bhwGpkRpBDiicOaUUd-FziCUuPAK41ykjiUeE8Z53KcgslZUk+isB2DsohZFqLroUFujbe2NEMVAnBWANyQkEU0GsgS7A9sOZEzIH0gZ3hhmjNQOMmO6gIrTO2LsemIBmSpEFIUPAAAJZAABZMCl4xaRDiclNuIA0pSpAL4OJ8x5WpTFnEhVh8PnTBVa3YcarFWUtdPq01hrtUAClegAHks5q2oYKKgEA6yoCRdgFFQIsC0hoD3aATIelLR6UGHMVwbivAjBMl4sZPiVDgFgSyRRRBJ3jBTJN0gQRYCwN4h4Pg7jsAUSMTN6hRCgHQHOUEvwKA7GPFsiA+oBiICitAB4+by2ZuzUUJQNB5CNrOi24QPVFlYgrQgJtDw3hxn6YwGp-QwCQGsCW8AapeStV+KQba5g4yHD9jqRA1DaETvYBAXQZbLklrjPrTd7BaxYDsQIAADOpe97wgA) for dynamically loading these definitions. Notice it does not give errors for referencing these, without having to filter. However it takes more time to download the definition files. We may cache them or import them during build.

**Comment by mcintyre94** [comment]
Ah snap, I just opened https://github.com/slipHQ/run-wasm/issues/69 at the same time which is a dupe of this! I figured out `lib` was missing from compiler options but adding them wasn't working. Your link here is extremely helpful and shows exactly what I needed to use to get them working, thankyou! :) Also good to see that the only required option seems to be `lib`.

**Comment by hatemhosny** [comment]
> FWIW for our use case I think it makes sense to preload them in the constructor - I don't think we need to support changing the options on the fly between code executions.

I agree

**Comment by KagenLH** [comment]
Is somebody already working on this? If not I'd like to fork and try to implement the fix mentioned in the discussion of this thread.

**Comment by mcintyre94** [comment]
@KagenLH I was going to shortly but haven't started so please go ahead :)

**Comment by shadab14meb346** [comment]
I was also looking into this, also to get familiar with the codebase.
So I went through the complete flow of how the `TSClient` instances get called with the click of the `Run Code` button.
So for this, I have commented on [this](https://github.com/slipHQ/run-wasm/pull/79) PR.
@KagenLH I can be wrong in the comment in PR. But just wanted to point out my observation.

**Comment by kennethcassel** [comment]
Closed with #79
