### ISSUE TITLE
Add dark mode to runwasm.com

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#70]
**Is your feature request related to a problem? 
Yes, when I view the site at night I feel like I should be wearing sunglasses. 

**Describe the solution you'd like**
A darkmode toggle for the site.

**Describe alternatives you've considered** 
I've considered wearing sunglasses to view the site at night.

**Additional context**

Here is a screenshot of a color palette we are probably going to use at Slip for the authoring tool. 

![color_pallete](https://user-images.githubusercontent.com/22961671/135345104-3dc1a7af-0c8c-4da0-990b-34da41b4a7d5.png)

Primary Background (Dark Gray): #1A1A1A
Secondary Background (Lighter Gray): #252525
Highlight: #323232
White: #FFFFFF

**Comment by pouannes** [comment]
I'll take it :) I'll probably use [next-themes](https://www.npmjs.com/package/next-themes) if that's fine with you

**Comment by shadab14meb346** [comment]
I am also interested in taking this.

**Comment by kennethcassel** [comment]
> I'll take it :) I'll probably use [next-themes](https://www.npmjs.com/package/next-themes) if that's fine with you

I think tailwind dark mode should be sufficient https://tailwindcss.com/docs/dark-mode

**Comment by pouannes** [comment]
@shadab14meb346 you can take it if you want :)

**Comment by devonzara** [comment]
Likewise, I can take it if nobody else does. Should be pretty easy to implement with Tailwind.
