### ISSUE TITLE
Screen flashes when changing pages in dark mode

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#75]
**Describe the bug** 
In dark mode, the screen flashes when navigating to a new page

**To Reproduce** Steps to reproduce the behavior:

Visit runwasm.com in dark mode. 
Click on one of the internal links in header. 
See white flash.

**Expected behavior** 
No flashing when navigating pages.

**Screenshots** 

https://user-images.githubusercontent.com/22961671/135466053-fe06de2b-7cac-4c92-a958-2eb665a5f617.mov

**Comment by Deep-Codes** [comment]
@jsjoeio can I take this up?

**Comment by jsjoeio** [comment]
I'm just a contributor like you but, I think so! Go for it!
