### ISSUE TITLE
theme flickers on load

### ISSUE THREAD

**Issue by Deep-Codes** [slipHQ/run-wasm#78]
**Describe the bug** A clear and concise description of what the bug is.

Visiting run-wasm.com will give a flicker in theme (light => dark).

> I would fix this I already did this in [100ms Docs](https://docs.100ms.live/javascript/v2/guides/react-quickstart)

**To Reproduce** Steps to reproduce the behavior:

Visiting run-wasm.com from a new tab.

https://user-images.githubusercontent.com/61158210/135500101-1f9ec3d8-0d6d-40c1-b14f-13002b0e98e6.mp4

**Desktop (please complete the following information):**

- Device: Macbook Pro
- OS:  Catalina
- Browser:  Brave
- Version: Latest

**Comment by jsjoeio** [comment]
I think this is a duplicate of #75

**Comment by Deep-Codes** [comment]
> I think this is a duplicate of #75

Smh Closing
