### ISSUE TITLE
Add Monaco code editor to the example-nextjs project

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#8]
Currently using a text area for the code input. 

We should use a proper in-browser code editor.  Use the Monaco code editor instead of a text-area.
This package for using monaco easily with React looks like a good option https://github.com/suren-atoyan/monaco-react

**Comment by kennethcassel** [comment]
Bonus points for adding it to the example react folder as well!

**Comment by ntindle** [comment]
IMO Monaco is very much worth considering

**Comment by kennethcassel** [comment]
Would be totally down for Monaco! 

The idea here is: 

1. Get a code editor in the example projects, so people can actually play around with writing and executing the code in browser
2. Evaluate which code editor we'd like to ship with the run-wasm library itself

Ideally I think the code editor we end up shipping with the library should be highly theme-able, easy to use, and well maintained.


Monaco looks interesting since it powers vs code. 

Current options I'm aware of:
react-ace 
CodeMirror
Monaco

**Comment by ntindle** [comment]
I reviewed this extensively recently (past month) for a project for work. Those three are probably the best options. Which you choose depends on many things.

**Comment by kennethcassel** [comment]
looks like Monaco is a good option. let's go with that. Going to update the issue. 

The biggest knock against monaco was no mobile support, but it seems to have been recently fixed https://github.com/microsoft/monaco-editor/issues/246

**Comment by kennethcassel** [comment]
Resolved with @nikolaystrikhar's pr
