### ISSUE TITLE
Add link to GitHub in the example-nextjs project

### ISSUE THREAD

**Issue by kennethcassel** [slipHQ/run-wasm#9]
Add a link back to this GitHub repo so folks who visit the runwasm.com site can easily navigate here and contribute/view the project

**Comment by govindgoel** [comment]
@kennethcassel I can take this up

**Comment by kennethcassel** [comment]
@govindgoel of course! Go for it :)

**Comment by nikolaystrikhar** [comment]
Sorry, I forgot to mention this issue in my PR commit https://github.com/slipHQ/run-wasm/pull/28!

**Comment by kennethcassel** [comment]
Thanks @nikolaystrikhar!

**Comment by govindgoel** [comment]
Yeah no issues, I will take up another issue and get that done asap.
Thanks
